# For Java 8, try this
# FROM openjdk:17-jdk-alpine

# For Java 11, try this
FROM adoptopenjdk/openjdk11:alpine-jre

# Refer to Maven build -> finalName
ARG JAR_FILE=target/spring-pavote-0.0.1.jar

# cd /opt/app
WORKDIR /opt/app

# cp target/spring-pavote-0.0.1.jar /opt/app/app.jar
COPY ${JAR_FILE} app.jar

# java -jar /opt/app/app.jar
ENTRYPOINT ["java","-jar","app.jar"]
